sonar.projectKey=amerta-backend
sonar.host.url=https://sonarqube.cs.ui.ac.id
sonar.login=${SONAR_TOKEN}

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.test.inclusions=src/test/java/**/*.java

sonar.java.coveragePlugin=jacoco
sonar.coverageReportPaths=build/reports/tests/test/index.html

sonar.verbose=true